export const PLAUSIBLE_GOALS = {
  DARK_MODE: 'DARK_MODE', // NOPE
  EDUCATION: 'EDUCATION', // works
  LINK_AFTER_RUSSIA: 'LINK_AFTER_RUSSIA', // works
  LINK_DOTU: 'LINK_DOTU', // works
  LINK_PORTFOLIO: 'LINK_PORTFOLIO', // works
  LINK_TETRIS: 'LINK_TETRIS', // works
  LINK_TVAR: 'LINK_TVAR', // works
  MENU_LOCALE_CS: 'MENU_LOCALE_CS', // NOPE
  MENU_LOCALE_EN: 'MENU_LOCALE_EN', // NOPE
  MENU_LOCALE_RU: 'MENU_LOCALE_RU', // NOPE
  VIDEO_DOTU_STARTED: 'VIDEO_DOTU_STARTED', // NOPE
  VIDEO_DOTU_FINISHED: 'VIDEO_DOTU_FINISHED', // NOPE
  VIDEO_AFTER_RUSSIA_STARTED: 'VIDEO_AFTER_RUSSIA_STARTED', // works
  VIDEO_AFTER_RUSSIA_FINISHED: 'VIDEO_AFTER_RUSSIA_FINISHED', // works
  GITHUB: 'GITHUB', // works
  LINKED_IN: 'LINKED_IN', // works
} as const;

export type PlausibleGoal = (typeof PLAUSIBLE_GOALS)[keyof typeof PLAUSIBLE_GOALS];
